POST http://localhost:8080/payroll/reimbursements

{
    "employeeName": "Jimmy Nesham",
    "employeeNumber": "2114",
    "reportingLead": "Erick Watson",
    "accountID": "3247c2ad-7aea-4b85-aa8b-59c7db98d49a",
    "reimbursementDetails": {
        "name": "Support Services Reimbursement",
        "calculationType": "FixedAmount",
        "reimbursementCategory": "SUPPORT_SERVICES",
        "standardAmount": 1000,
        "standardTypeOfUnits": "MONTHLY",
        "standardRatePerUnit": 1.5,
        "claimDate": "2023-08-10T03:25:37.0873765",
        "urlForReceipt": "https://drive.google.com/file/1IcurS3n1KHGuGwCECpIOXP1BP-qqQTKC",
        "urlForBankStatement": "https://drive.google.com/file/1Icur243msfKHGuGwCECpIOXP1BP-qqQTKC"
    },
    "comments": "Urgent"
}
