POST http://localhost:8080/bulbs/switch

{
    "roomNo" : 15,
    "state" : "DIM"
}

###

POST http://localhost:8080/bulbs/switch

{
    "roomNo" : 9,
    "state" : "DIM"
}

###

POST http://localhost:8080/bulbs/switch

{
    "roomNo" : 15,
    "state" : "ON"
}
