POST http://localhost:8080/bulbs/add_route

{
    "deviceId" : "EM54234",
    "roomNo" : "12"
}

###

POST http://localhost:8080/bulbs/add_route

{
    "deviceId" : "EM12399",
    "roomNo" : "15"
}

###

GET http://localhost:8080/bulbs/2
